### ISSUE TITLE
[FEATURE] Make rToken contract upgradable

### ISSUE THREAD

**Issue by hellwolf** [decentral-ee/rtoken-contracts#3]
Acceptance Criteria:

- Follow https://blog.openzeppelin.com/proxy-patterns/
- Test cases

**Comment by pi0neerpat** [comment]
I can take this! 

Planning to implement [EIP-1822](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1822.md) which I helped author. EIP1822 is a complete implementation of a proxy storage slot with a generic upgradeability pattern. Just FYI, [EIP 1967](https://github.com/ethereum/EIPs/blob/b33f811d78bdc3b95f9217c8f726a5001d747b76/EIPS/eip-1967.md) from Open Zeppelin shares the same proxy storage slot paradigm, but doesn't include the upgradeability pattern.

The basics of the 1822 pattern will go like this:
- Storage slot of the library contract is stored at `sslot(<someHashedValue>)`
- All contract storage will be moved to a storage contract. This is to encourage "append-only" for adding new variables, so there is no storage collision in future versions of the contract.
- All calls to the proxy made after constructor will be delegated (including the calls to perform an upgrade).
- 1822 includes a safety mechanism to prevent "getting stuck" which checks that the new library you are upgrading is indeed upgradeable.
- I will also add a Library Lock to prevent the Parity Wallet hack

**Comment by hellwolf** [comment]
I believe the bounty has been released to your account @pi0neerpat, good work, thank you!

**Comment by pi0neerpat** [comment]
Got it thanks!
