### ISSUE TITLE
User generated reports on interest accrued

### ISSUE THREAD

**Issue by vrortvedt** [decentral-ee/rtoken-contracts#8]
Acceptance criteria:

- Enable users to generate time-bound reports as to amounts of interest earned and amounts of interest directed to other addresses

- Could be contract read function or subgraph index, tradeoffs should be discussed

Rationale: Tax reporting - users reporting their interest income to local tax authorities need to be able to track that information, and they may also wish to be able to track interest directed to tax-deductible charity addresses

**Comment by hellwolf** [comment]
Considered to be a dup of #6 and #14
